production:
  solr:
    hostname: localhost
    port: 8088
    log_level: WARNING
    path: /solr-fetch
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    hostname: localhost
    port: 8982
    log_level: INFO
    path: /solr/development

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: DEBUG
    path: /solr/test
    
