
roles:
  apache:
    packages: [apache2, apache2-utils, libapache2-mod-proxy-html, libcurl4-openssl-dev, libapache2-mod-xsendfile libapache2-mod-rewrite]
  web_tools:
    packages: [apache2, apache2-utils, libapache2-mod-proxy-html, libcurl4-openssl-dev, libapache2-mod-xsendfile libapache2-mod-rewrite]
